app/urls.py
from django.urls import path
from .views import IndexView, BlogView, AboutView, PostDetailView, \
    PersonalAccountView, LoginView, AboutServiceView, LogoutView


app_name = 'app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blog/<slug:name>/', BlogView.as_view(), name='blog'),
    path('about/', AboutView.as_view(), name='about'),
    path('about/service/', AboutServiceView.as_view(), name='about-service'),
    path('blog/post/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('personal/', PersonalAccountView.as_view(), name='personal-account'),
    path('login/<param>/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # Чтобы была возможность подгрузить файл с настройками
from django.conf.urls.static import static  # Чтобы подгрузить обработчик статических файлов

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавление путей для обработки
    # медиафайлов в Django(по умолчанию не обрабатывается, поэтому пишем, чтобы обрабатывалась как статика). Для режима
    # продакшн (Debug=False) нужно использовать другие сервисы (не Django) для обработки медиафайлов.
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),  # для Django Debug Toolbar
    ]

app/templates/app/base_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block head %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
{% block title %}
<!--    <title>Stand CSS Blog by TemplateMo</title>-->
{% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'app/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'app/assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'app/assets/css/owl.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
{% endblock %}
  </head>

  <body>
{% block header %}
    {% block loader %}
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    {% endblock %}
    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'app:index' %}"><h2>Блог-платформа</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:about-service' %}">О сервисе</a>
              </li>
              {% if not user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'app:login' 'signin'%}">Авторизироваться</a>
              </li>
                {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'app:logout' %}">Выйти</a>
              </li>
                    <li class="nav-item">
                <a class="nav-link" href="{% url 'app:personal-account' %}">Личный кабинет</a>
              </li>
                    Привет, {{ user.username }}
              </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
{% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
{% block banner %}

{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.

                 | Дизайн: <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">TemplateMo</a>
                  | Разработано в ознакомительных целях на:  <a href="https://www.djangoproject.com/" target="_parent">Django</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
{% endblock %}

{% block script %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'app/assets/js/custom.js' %}"></script>
    <script src="{% static 'app/assets/js/owl.js' %}"></script>
    <script src="{% static 'app/assets/js/slick.js' %}"></script>
    <script src="{% static 'app/assets/js/isotope.js' %}"></script>
    <script src="{% static 'app/assets/js/accordions.js' %}"></script>

{% endblock %}
{% block add_script %}

{% endblock %}
  </body>
</html>

app/templates/app/blog.html
{% extends 'app/base_blog.html' %}
{% load static %}
{% block title %}
<title>Stand Blog Posts</title>
{% endblock %}

{% block loader %}
 <!-- Убирает мерцание при загрузке -->
{% endblock %}

{% block banner %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>{{ blog.name }}</h4>
                <h2>{{ blog.headline }}</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    {% endblock %}
    <!-- Banner Ends Here -->



{% block content %}
    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                  {% for post in blog.entryes.all %}
                <div class="col-lg-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ post.image.url }}" alt="">
                    </div>
                    <div class="down-content">
{#                      <span>Lifestyle</span>#}
                      <a href="{% url 'app:post-detail' post.slug_headline %}"><h4>{{ post.headline }}</h4></a>
                      <ul class="post-info">
                        <li>
                          {% for author in entry.authors.all %}
                            <a href="#">{{ author.user }}</a>{% if not forloop.last %}<a>, </a>{% endif %}
                          {% endfor %}
                        </li>
                        <li><a href="#">{{ post.pub_date|date:"d M Y, H:i"  }}</a></li>
                        <li><a href="{% url 'app:post-detail' post.slug_headline %}#comments">{{ post.number_of_comments }} Комментариев</a></li>
                      </ul>
                      <p>{{ post.summary }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in post.tags.all %}
                              <li><a href="#">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}</li>
                              {% endfor %}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                  {% endfor %}

                <div class="col-lg-12">
                  <ul class="page-numbers">
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="#">
                      <input type="text" name="q" class="searchText" placeholder="Искать..." autocomplete="on">
                    </form>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Недавние посты</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for post in resent_posts %}
                          <li><a href="{% url 'app:post-detail' post.slug_headline %}">
                          <h5>{{ post.headline }}</h5>
                          <span>{{ post.pub_date|date:"d M Y, H:i"  }}</span>
                        </a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Другие блоги</h2>
                    </div>
                    <div class="content">
                      <ul>
                          {% for blog in blogs %}
                              <li><a href="{% url 'app:blog' blog.slug_name %}">- {{ blog.name }}</a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                  <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Теги блога</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for tag in blog_tags %}
                        <li><a href="#">{{ tag.name }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base_blog.html' %}
{% load static %}

{% block title %}
<title>Test Blog</title>
{% endblock %}

{% block banner %}
    <div class="main-banner header-text">
      <div class="container-fluid">
      <div class="actual-content">
            <h2 class="actual-title">Актуальное</h2>
        </div>
        <div class="owl-banner owl-carousel">
            {% for entry in most_entryes %}
          <div class="item">
            <img src="{{ entry.image.url }}" alt="">
            <div class="item-content">
              <div class="main-content">
                <div class="meta-category">
                  <a href="{% url 'app:blog' entry.blog.slug_name %}"><span>{{ entry.blog.name }}</span></a>
                </div>
                <a href="{% url 'app:post-detail' entry.slug_headline %}"><h4>{{ entry.headline }}</h4></a>
                <ul class="post-info">
                  <li>
                      {% for author in entry.authors.all %}
                        <a href="#">{{ author.user }}</a>{% if not forloop.last %}<a>, </a>{% endif %}
                      {% endfor %}
                  </li>
                  <li><a href="#">{{ entry.pub_date|date:"d M Y, H:i"  }}</a></li>
                  <li><a>{{ entry.number_of_comments }} Комментариев</a></li>
                </ul>
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->
{% endblock %}

<!-- Главная страница -->
{% block content %}
    <section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                {% for entry in entryes %}
                  <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ entry.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <span>{{ entry.blog.name }}</span>
                      <a href="{% url 'app:post-detail' entry.slug_headline %}"><h4>{{ entry.headline }}</h4></a>
                      <ul class="post-info">
                        <li>
                          {% for author in entry.authors.all %}
                            <a href="#">{{ author.user }}</a>{% if not forloop.last %}<a>, </a>{% endif %}
                          {% endfor %}
                        </li>
                        <li><a href="#">{{ entry.pub_date|date:"d M Y, H:i"  }}</a></li>
                        <li><a>{{ entry.number_of_comments }} Комментариев</a></li>
                      </ul>
                      <p>{{ entry.summary }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in entry.tags.all %}
                              <li><a href="#">{{ tag.name }}</a>{% if not forloop.last %},{% endif %}</li>
                              {% endfor %}
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Вконтакте</a>, </li>
                              <li><a href="#">Телеграм</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                  {% endfor %}
              <div class="col-lg-12">
                  <ul class="page-numbers">
                      <!--Пагинатор -->
                      {% if entryes.has_previous %}
                        <li><a href="?page=1">1</a></li>
                        <li><a href="?page={{ entryes.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a></li>
                      {% endif %}
                      <li class="active"><a>{{ entryes.number }}</a></li>
                      {% if entryes.has_next %}
                          <li><a href="?page={{ entryes.next_page_number }}"><i class="fa fa-angle-double-right"></i></a></li>
                          <li><a href="?page={{ entryes.paginator.num_pages}}">{{ entryes.paginator.num_pages }}</a></li>
                      {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="#">
                      <input type="text" name="q" class="searchText" placeholder="Поиск ..." autocomplete="on">
                    </form>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Свежее</h2>
                    </div>
                    <div class="content">
                      <ul>
                            {% for entry in fresh_entryes %}
                          <li><a href="{% url 'app:post-detail' entry.slug_headline %}">
                          <h5>{{ entry.headline }}</h5>
                          <span>{{ entry.pub_date|date:"d M Y, H:i"  }}</span>
                        </a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Блоги</h2>
                    </div>
                    <div class="content">
                      <ul>
                          {% for blog in blogs %}
                              <li><a href="{% url 'app:blog' blog.slug_name %}">- {{ blog.name }}</a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Теги</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for tag in tags %}
                        <li><a href="#">{{tag.name}}</a></li>
                        {% endfor %}
                        <div class="col-lg-12">
                          <div class="main-button">
                            <a href="#">Показать все теги</a>
                          </div>
                        </div>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

app/templates/app/post_detail.html
{% extends 'app/base_blog.html' %}
{% load static %}

{% block title %}
<title>Stand Blog - Post Details</title>
{% endblock %}

{% block loader %}
 <!-- Убирает мерцание при загрузке -->
{% endblock %}

{#{% block banner %}#}
{#    <!-- Page Content -->#}
{#    <!-- Banner Starts Here -->#}
{#    <div class="heading-page header-text">#}
{#      <section class="page-heading">#}
{#        <div class="container">#}
{#          <div class="row">#}
{#            <div class="col-lg-12">#}
{#              <div class="text-content">#}
{#                <h4>Post Details</h4>#}
{#                <h2>Single blog post</h2>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </section>#}
{#    </div>#}
{#{% endblock %}#}
    <!-- Banner Ends Here -->
{% block content %}
    <section class="blog-posts grid-system" style="margin-top: 0px">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post-blog">
                    <div class="blog-thumb">
                      <img src="{{ entry.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <span>{{ entry.blog.name }}</span>
                      <h4>{{ entry.headline }}</h4>
                      <ul class="post-info">
                        <li>
                          {% for author in entry.authors.all %}
                            <a href="#">{{ author.user }}</a>{% if not forloop.last %}<a>, </a>{% endif %}
                          {% endfor %}
                        </li>
                        <li><a href="#">{{ entry.pub_date|date:"d M Y, H:i"}}</a></li>
                        <li><a href="#comments">{{ entry.number_of_comments }} Комментариев</a></li>
                      </ul>
                      {{ entry.body_text|safe }}
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in entry.tags.all %}
                              <li><a href="#">{{tag.name}}</a>{% if not forloop.last %},{% endif %}</li>
                              {% endfor %}
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Вконтакте</a>, </li>
                              <li><a href="#">Телеграм</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2 id="comments">Комментарии</h2>
                    </div>
                  <!-- Блок комментариев -->
                    <div class="content">
                      <ul>
                        {% for comment in entry.comments.all %}
                            {% if not comment.parent %}
                                <li>
                                    <div class="author-thumb">
                                        <img src="{{ comment.user.user_profile.avatar.url }}" alt="Фото профиля">
                                    </div>
                                    <div class="right-content" id="comment-id-{{ comment.id }}">
                                        <h4>{{ comment.user }}<span>{{ comment.created_at|date:"d M Y, H:i" }}</span></h4>
                                        <p>{{ comment.text }}</p>
                                    <!-- Проверка, что пользователь автор и он числится среди авторов статьи или пользователь часть персонала сайта -->
                                    <!-- Тогда будет возможность ответить на комментарий -->
                                         {% if user.author_profile and user.author_profile in entry.authors.all or user.is_staff %}
                                        <p><a href="#" onclick="showReplyForm({{ comment.id }}); return false;">Ответить</a></p>
                                         {% endif %}
                                    </div>
                                </li>
                                <!-- Скрытая форма для ответа -->
                                <div class="reply-form" id="reply-form-{{ comment.id }}" style="display: none;">
                                    <form action="{% url 'app:post-detail' entry.slug_headline %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="parent" value="{{ comment.id }}">
                                        <div class="col-lg-12">
                                            <textarea name="text" rows="3" placeholder="Введите свой комментарий" required=""></textarea>
                                        </div>
                                        <div class="col-lg-12">
                                            <button type="submit" class="main-button">Опубликовать</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- Отображение дочерних комментариев -->
                                {% for child in comment.children.all %}
                                    <li class="replied">
                                        <div class="author-thumb">
                                            <img src="{{ child.user.user_profile.avatar.url }}" alt="Фото профиля автора">
                                        </div>
                                        <div class="right-content">
                                            <h4>{{ child.user }}<span>{{ child.created_at|date:"d M Y, H:i" }}</span></h4>
                                            <p>{{ child.text }}</p>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        {% empty %}
                        <p>Будьте первым, кто оставит комментарий</p>
                        {% endfor %}
                      </ul>
                    </div>
                  <!-- Конец блока комментариев -->
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Оставить комментарий</h2>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="content">
                          <form id="comment" action="{% url 'app:post-detail' entry.slug_headline %}" method="post">
                            {% csrf_token %}
                              <div class="row">
                                  <div class="col-lg-12">
                                    <fieldset>
                                      <textarea name="text" rows="6" id="message" placeholder="Введите свой комментарий" required=""></textarea>
                                    </fieldset>
                                  </div>
                                  <div class="col-lg-12">
                                    <fieldset>
                                      <button type="submit" id="form-submit" class="main-button">Опубликовать</button>
                                    </fieldset>
                                  </div>
                            </div>
                          </form>
                        </div>
                    {% else %}
                         <div class="content">
                        <div class="col-lg-12">
                                Чтобы просматривать комментарии <a href="{% url 'app:login' 'signin'%}?next={% url 'app:post-detail' entry.slug_headline %}">авторизируйтесь!</a>
                        </div>
                         </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                      <div class="post">
                          <form id="search_form" name="gs" method="GET" action="#">
                      <input type="text" name="q" class="searchText" placeholder="Найти..." autocomplete="on">
                    </form>
                      </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Другие посты этого блога</h2>
                    </div>
                    <div class="content">
                      <ul>
                            {% for entry in blog_entryes %}
                          <li><a href="{% url 'app:post-detail' entry.slug_headline %}">
                          <h5>{{ entry.headline }}</h5>
                          <span>{{ entry.pub_date|date:"d M Y, H:i"  }}</span>
                        </a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Блоги</h2>
                    </div>
                    <div class="content">
                      <ul>
                          {% for blog in blogs %}
                              <li><a href="{% url 'app:blog' blog.slug_name %}">- {{ blog.name }}</a></li>
                          {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Теги блога</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for tag in blog_tags %}
                        <li><a href="#">{{ tag.name }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}
{% block add_script %}
<script>
let currentReplyForm = null;

function showReplyForm(commentId) {
    // Скрыть текущую открытую форму, если она есть
    if (currentReplyForm) {
        currentReplyForm.style.display = 'none';
    }

    // Найти и показать новую форму
    let form = document.getElementById('reply-form-' + commentId);
    if (form) {
        form.style.display = 'block';
        currentReplyForm = form;  // Обновляем текущую открытую форму
    }
}
</script>
{% endblock %}